# docker-compose.production.yml
version: '3'

volumes:
  pg_data:
  static_volume:

# Всё отличие — заменяем build на image и указываем, какой образ использовать
services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: viktorkors/kittygram_backend_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
  frontend:
    image: viktorkors/kittygram_frontend # Качаем с Docker Hub
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: viktorkors/kittygram_gateway  # Качаем с Docker Hub
    env_file: .env
    volumes:
      - static_volume:/staticfiles/
    ports:
      - 9000:80
